name: Makefile CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Cleanup
      run: rm -f ./src/main.o ./src/mod/mod.o app
      
    - name: Run tests
      run: make test

    - name: Prepare Build
      run: make build

    - name: Install dependencies
      run: make

    - name: Run check
      run: make check

    - name: Run distcheck
      run: make distcheck
